# Generated by Django 4.2.5 on 2023-10-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(default='7:00 PM', max_length=20)),
                ('team1', models.CharField(max_length=100)),
                ('result1', models.IntegerField()),
                ('result2', models.PositiveIntegerField()),
                ('team2', models.CharField(max_length=100)),
                ('group', models.CharField()),
            ],
        ),
    ]
