# Generated by Django 4.2.5 on 2023-10-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0002_fixtures_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='round',
            field=models.CharField(choices=[('Round 1', 'Round 1'), ('Semi-Finals', 'Semi-Finals'), ('Finals', 'Finals')], default='Round 1', max_length=20),
        ),
    ]
