# Generated by Django 4.2.5 on 2023-10-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_goals_customuser_points_customuser_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
