# Generated by Django 4.2.5 on 2023-10-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('role', models.CharField(choices=[('goal_keeper', 'Goal Keeper'), ('defender', 'Defender'), ('midfielder', 'Midfielder'), ('forward', 'Forward')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='authentication.customuser')),
            ],
        ),
    ]
