# Generated by Django 4.2.5 on 2023-10-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('user_side', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='authentication.customuser'),
        ),
    ]
